//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeInfo()
        {
            this.Attendences = new HashSet<Attendence>();
            this.Salaries = new HashSet<Salary>();
        }
    
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public bool EmployeeGender { get; set; }
        public string EmployeeEmail { get; set; }
        [DataType(DataType.Password)]
        public string EmployeePassword { get; set; }
        public int EmployeePhone { get; set; }
        public string Address { get; set; }
        public Nullable<int> DesignationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendence> Attendences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salaries { get; set; }
        public virtual Designation Designation { get; set; }
    }
}
