//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int SalaryId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> Bonous { get; set; }
        public Nullable<decimal> Allownce { get; set; }
        public Nullable<decimal> ToltalSalarey { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual EmployeeInfo EmployeeInfo { get; set; }
    }
}
